apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: "ACCESS_KEY_PLACEHOLDER"
  access_key_secret: "SECRET_KEY_PLACEHOLDER"
  bucketnames: "BUCKETNAME_PLACEHOLDER"
  endpoint: "https://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc:80"
